version: 2
updates:
  - package-ecosystem: pub
    directory: /apps/mobile
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /apps/mobile/android
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
