import 'package:uuid/uuid.dart';

import '../domain/distance_unit.dart';
import '../domain/imported_route.dart';
import '../domain/ride_library_organisation.dart';
import '../domain/ride_plan.dart';
import 'measurement_formatter.dart';
import 'road_routing.dart';
import 'route_verification.dart';

/// A plan, routed.
class RidePlanRoute {
  const RidePlanRoute({
    required this.route,
    required this.distanceMeters,
    required this.duration,
    this.twistinessScore,
    this.warnings = const [],
    this.verification,
  });

  final ImportedRoute route;
  final double distanceMeters;
  final Duration duration;
  final double? twistinessScore;
  final List<String> warnings;

  /// What checking the route against the plan's preferences found, when the
  /// routing service checks (#840). Shown on the plan surface as the review
  /// shows it.
  final RouteVerification? verification;
}

/// Turns a [RidePlan] into a road route (#847).
///
/// Shaping points go to the router as non-stopping controls through
/// [routeThroughWithShaping] — OSRM's `waypoints=` and Valhalla's `through` —
/// so only named places split the route into legs, and a drawn adjustment can
/// never become an "arrive at your destination" in the middle of a road
/// (#839).
///
/// The routing service is the host's planning service, so a plan is routed —
/// and checked against its preferences — exactly as a destination is.
class RidePlanRouter {
  RidePlanRouter({
    required this.routingService,
    String Function()? idFactory,
    DateTime Function()? clock,
  }) : _idFactory = idFactory ?? const Uuid().v4,
       _clock = clock ?? DateTime.now;

  final RoadRoutingService routingService;
  final String Function() _idFactory;
  final DateTime Function() _clock;

  static const startSymbol = 'Flag, Blue';
  static const stopSymbol = 'Flag, Green';
  static const destinationSymbol = 'Flag, Red';

  /// Routes [plan] from [currentLocation] when it starts there.
  ///
  /// [base] is the route being edited, when there is one: its identity, its
  /// library details and its marker decisions carry over, and so does its name
  /// unless that name only ever said where it went.
  Future<RidePlanRoute> route(
    RidePlan plan, {
    GeoPoint? currentLocation,
    ImportedRoute? base,
    DistanceUnit distanceUnit = DistanceUnit.kilometres,
  }) async {
    final destination = plan.destination;
    if (destination == null) {
      throw const FormatException('Choose a destination.');
    }
    final controls = plan.controls(currentLocation: currentLocation);
    if (controls == null) {
      throw const FormatException(
        'Your location is not known yet. Choose a start, or allow location '
        'access.',
      );
    }
    // #839's non-stopping call: shaping points pass through, and only named
    // places end a leg.
    final result = await routeThroughWithShaping(
      routingService,
      controls.points,
      shapingPointIndexes: controls.shapingPointIndexes,
      preferences: plan.preferences,
    );

    final warnings = <String>[
      // Raised on what came back, as `DestinationRoutePlanner` does (#303).
      if (result.maneuvers.isEmpty)
        PreferenceAwareRoadRoutingService.motorcycleManeuverWarning,
    ];
    final named = controls.namedPlaces;
    final id = base?.id ?? _idFactory();
    final route = ImportedRoute(
      id: id,
      sourceRouteId: base?.sourceRouteId,
      derivedFromRouteId: base?.derivedFromRouteId,
      organisation: base?.organisation ?? const RideLibraryOrganisation(),
      name: _nameFor(destination, base),
      description:
          'Road route generated by Tail End Charlie. '
          '${MeasurementFormatter(distanceUnit).distance(result.distanceMeters)}, '
          '${_durationLabel(result.duration)}. '
          '${plan.preferences.summary}',
      importedAt: base?.importedAt ?? _clock().toUtc(),
      sourceFileName: base?.sourceFileName ?? 'ride-relay-destination-$id.gpx',
      paths: [
        RoutePath(
          kind: RoutePathKind.track,
          name: 'Road route to ${shortPlaceLabel(destination.label)}',
          points: result.points,
        ),
      ],
      waypoints: [
        for (final (index, place) in named.indexed)
          place.toWaypoint(
            defaultSymbol: index == 0
                ? startSymbol
                : index == named.length - 1
                ? destinationSymbol
                : stopSymbol,
          ),
      ],
      shapingPoints: plan.shapingPoints,
      maneuvers: result.maneuvers,
      // Rejections are kept by position, so they still find their junction on
      // a recalculated route and drop out quietly where it no longer has one
      // (#179).
      markerReview: base?.markerReview ?? MarkerPlanReview.empty,
      preferences: plan.preferences,
      plannedDuration: result.duration,
    );
    return RidePlanRoute(
      route: route,
      distanceMeters: result.distanceMeters,
      duration: result.duration,
      twistinessScore: result.twistinessScore,
      warnings: List.unmodifiable(warnings),
      verification: result.verification,
    );
  }

  /// A route named for where it went is renamed when that changes; a route
  /// the rider or a file named keeps its name.
  static String _nameFor(RidePlanPlace destination, ImportedRoute? base) {
    final planned = RidePlan.nameFor(destination);
    if (base == null) return planned;
    final previousDestination = base.waypoints.lastOrNull;
    final previousName = previousDestination?.name;
    final wasAutomatic =
        previousName != null &&
        base.name ==
            RidePlan.nameFor(
              RidePlanPlace(
                point: previousDestination!.point,
                label: previousName,
              ),
            );
    return wasAutomatic ? planned : base.name;
  }
}

String _durationLabel(Duration duration) {
  final minutes = (duration.inSeconds / 60).round();
  if (minutes < 60) return '$minutes min';
  final hours = minutes ~/ 60;
  final remainder = minutes % 60;
  return remainder == 0 ? '$hours hr' : '$hours hr $remainder min';
}
